### ISSUE TITLE
Dyson Local integration success, but didn't update

### ISSUE THREAD

**Issue by yauyauwind** [shenxn/ha-dyson#33] opened 2021-03-31 09:53 UTC
Hello All,

I use Docker HA 2021.3.4 with latest dyson cloud and dyson local
I setup dyson cloud first, then dyson local add, and discover my TP04
and then integration is added success
however I found that the status will never update
it's only get the value from the first times setup or restart the HA get the once status
and then keep the temp or hum or another status the same value
What is the problem??

Thanks~

**Comment by yogoo** [comment] 2021-04-01 10:39
I'm seeing the same behavior for about a week now. Sending commands works well, but reading the status doesn't update. 
Docker HA 2021.3.4 + ha-dyson 0.8.1 + HP04

**Comment by 1darklyte** [comment] 2021-04-04 16:01
Not entirely sure if related but for a few weeks I have had issues where the Thermostat card is not updating and it wont accept commands. 

Removed everything and set it up again with the same result.

Integration shows 11 entities under Dyson Local and confirmed I have the correct entity selected.

**Comment by googanhiem** [comment] 2021-04-06 12:12
Yes, we're looking into this issue in #24

So far it looks like a connection issue. My fans have a flakey wifi connection and HA-Dyson has a reconnection bug at the moment. For me it means after a couple hours this integration fails receiving state info (on/off, temp, pollution levels etc), you can still control the fan as its still sending out MQTT commands.

**Comment by shenxn** [comment] 2021-04-08 14:31
Try if the latest version fixed your problem.

**Comment by 1darklyte** [comment] 2021-04-08 16:45
I updated to the new version and tested. As of first try and first 5 min of testing it is working. Goes from Cooling to Heater to Off and back through the rotations.

**Comment by yogoo** [comment] 2021-04-09 18:57
Upgraded HA to 2021.4.0 yesterday, still using ha-dyson 0.8.1 with my HP04 and connectivity has been stable for the past 24h. Odd.

**Comment by googanhiem** [comment] 2021-04-09 19:28
Same, works great. Thanks again @shenxn

**Comment by yauyauwind** [comment] 2021-04-14 09:39
Hello All,

Updated HA and dyson local, cloud to the latest version, it's work great

Shenxn Thank you so much \^o^/

**Comment by shenxn** [comment] 2021-04-17 15:35
> Upgraded HA to 2021.4.0 yesterday, still using ha-dyson 0.8.1 with my HP04 and connectivity has been stable for the past 24h. Odd.
> 
> [Edit 2021-04-12] It finally failed [as reported earlier above] after 3 days. Upgraded to 0.10.0.

@yogoo Do you find anything related in log?

**Comment by yogoo** [comment] 2021-04-19 18:16
> > Upgraded HA to 2021.4.0 yesterday, still using ha-dyson 0.8.1 with my HP04 and connectivity has been stable for the past 24h. Odd.
> > [Edit 2021-04-12] It finally failed [as reported earlier above] after 3 days. Upgraded to 0.10.0.
> 
> @yogoo Do you find anything related in log?

@shenxn I couldn't find anything useful. I'm running HA in docker and it seems that the logs (/config/home-assistant.log) are cleared after every restart of HA.

**Comment by shenxn** [comment] 2021-04-29 14:41
@yogoo I'll close this for now. Feel free to open a new issue if you encountered this again.

**Closed by shenxn** 2021-04-29 14:41 UTC
