### ISSUE TITLE
This integration does not support configuration via the UI

### ISSUE THREAD

**Issue by Ulrar** [shenxn/ha-dyson#121] opened 2022-04-07 17:15 UTC
Hi,

Probably caused by the latest update to 2022.4 but both local and cloud integrations error out with this when trying to add them from the UI : 

```
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
 ```

Thank you

**Comment by ad2022uk** [comment] 2022-04-08 08:27
I have the same issue

**Comment by Flameeyes** [comment] 2022-04-08 08:52
Duplicate of #115

**Closed** 2022-04-08 16:45 UTC
