### ISSUE TITLE
Dyson i360 N223 missing entities

### ISSUE THREAD

**Issue by gfawkes66** [shenxn/ha-dyson#30] opened 2021-03-21 16:09 UTC
Hi,

I added my i360 a few updates ago and all was well. 
After updating to the latest version (local .81), i noticed i was missing the vacuum.xxx entity.
I am also only seeing the map in the cloud version.
I tried re-adding, but i still don't have the vacuum.xx entity, just the 2 power levels. Its being correctly identified as an i360 - N223.
I wonder if the definition has been accidentally broken when a new model was added?

Thanks!

**Comment by shenxn** [comment] 2021-03-23 02:02
Can you find anything related in log?

**Comment by gfawkes66** [comment] 2021-03-23 07:26
Hi,

ah yes, here is something from the logs
Thanks

2021-03-22 18:42:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 360 Eye robot vacuum for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 126, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 140, in async_setup_entry
    platform = await async_prepare_setup_platform(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 298, in async_prepare_setup_platform
    platform = integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 499, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 504, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/dyson_local/vacuum.py", line 122, in <module>
    VacuumHeuristPowerMode.QUIET: "Quiet",
  File "/usr/local/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: QUIET
2021-03-22 18:42:10 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform dyson_local does not generate unique IDs. ID JJ5-UK-JJA0124A-battery_charging already exists - ignoring binary_sensor.360_eye_robot_vacuum_battery_charging
2021-03-22 18:42:10 ERROR (MainThread) [homeassistant.components.sensor] Platform dyson_local does not generate unique IDs. ID JJ5-UK-JJA0124A-battery_level already exists - ignoring sensor.360_eye_robot_vacuum_battery_level
2021-03-22 18:42:10 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform wake_on_lan is taking over 10 seconds.

**Comment by iMiMx** [comment] 2021-03-24 22:35
Just added my 360 Heurist, checking the commits I see at least some support has been added for this model - also seeing 1 device and 3 only entities (charging state, battery, bin full).

Is late here now, will dig tomorrow.

**Comment by Panman1300** [comment] 2021-03-25 08:59
I have a 360 Eye (original model) but have the same problem, with one minor exception, I just get 2 entities - 'battery charging' and 'battery level'.

My log has an identical entry (except for the initial time, of course!).

**Comment by shenxn** [comment] 2021-04-08 14:34
It turns out to be a typo in libdyson. It should be fixed in the latest version. Can you test that?

**Comment by iMiMx** [comment] 2021-04-08 14:42
Initial test, seems to have resolved the problem - I now have 4 entities with my Heurist, the 4th being the vacuum

Much obliged.

**Comment by shenxn** [comment] 2021-04-08 14:44
Closing this issue. Feel free to re-open if it is not solved.

**Closed by shenxn** 2021-04-08 14:44 UTC

**Comment by Panman1300** [comment] 2021-04-08 15:20
I can confirm that control of my 360 Eye has returned.  Thank you! ✔✔
